version: '2'

services:
  scout:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_SECRET_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command: [ "python", "Scout2.py", "--help" ]
